name: Test
on: [push]
jobs:
  run:
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: E2E test
        uses: cypress-io/github-action@v2

      - name: Component test
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: npx cypress run-ct